config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/tests", to: 'pages#tests'
  get "/return_situation", to: 'situations#return_situation'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :stories do
    resources :situations do
      resources :choices, only: [:create, :destroy, :update]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :previous_situation, :class_name => 'Situation'
  belongs_to :next_situation, :class_name => 'Situation', dependent: :destroy, optional: true
end

app/models/situation.rb
class Situation < ApplicationRecord
  belongs_to :story

  has_many :child_choices, :class_name => 'Choice', :foreign_key => 'previous_situation_id', dependent: :destroy
  has_one :parent_choice, :class_name => 'Choice', :foreign_key => 'next_situation_id'

  has_one :start_situation

end

app/models/start_situation.rb
class StartSituation < ApplicationRecord
  belongs_to :story
  belongs_to :situation
end

app/models/story.rb
class Story < ApplicationRecord
  has_many :situations, dependent: :destroy
  has_one :start_situation

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
skip_before_action :authenticate_user!

  def create

    @story = Story.find(params[:story_id])
    @situation = Situation.find(params[:situation_id])
    @choice = Choice.new(choice_params)
    @choice.previous_situation = @situation

    if @choice.save
      redirect_to edit_story_situation_path(@story, @situation)
    else

    end
  end

  def update

    @story = Story.find(params[:story_id])
    @situation = Situation.find(params[:situation_id])
    @choice = Choice.find(params[:id])

    if @choice.update(choice_params)
      redirect_to edit_story_situation_path(@story, @situation)
    else
      render edit_story_situation(@story, @situation)
    end

  end

  def destroy

    @story = Story.find(params[:story_id])
    @situation = Situation.find(params[:situation_id])
    choice = Choice.find(params[:id])
    choice.destroy
    redirect_to edit_story_situation_path(@story, @situation)
  end

  private
  def choice_params
    params.require(:choice).permit(:description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :tests]

  def home
  end

  def tests
  end

end

app/controllers/situations_controller.rb
class SituationsController < ApplicationController
  skip_before_action :authenticate_user!


  def show

    # raise
    @story = Story.find(params[:story_id])
    @situation = Situation.find(params[:id])
    @child_choices = @situation.child_choices.sort_by{|c| c.id}
    @parent_choice = @situation.parent_choice
    @previous_situation = @parent_choice.previous_situation if @parent_choice
    @loop_start = @situation


  end

  def new


    @story = Story.find(params[:story_id])
    # @previous_situation = @parent_choice.previous_situation if @parent_choice
    @situation = Situation.new
    if params[:choice]
      @previous_choice = Choice.find(params[:choice])
      @previous_situation = @previous_choice.previous_situation
    end


  end

  def create
    @story = Story.find(params[:story_id])
    @situation = Situation.new(situation_params)
    @situation.story = @story

    if @situation.save
      if choice_params[:previous_choice]
        choice = Choice.find(choice_params[:previous_choice])
        choice.update(next_situation: @situation)
      else
        s = StartSituation.new
        s.story = @story
        s.situation = @situation
        s.save!
      end
      redirect_to edit_story_situation_path(@story, @situation)
    else
      render :new
    end
  end

  def edit
    @story = Story.find(params[:story_id])
    @situation = Situation.find(params[:id])
    @child_choices = @situation.child_choices.sort_by{|c| c.id}
    @parent_choice = @situation.parent_choice
    @previous_situation = @parent_choice.previous_situation if @parent_choice
    @choice = Choice.new
  end


  def update

    @story = Story.find(params[:story_id])
    @situation = Situation.find(params[:id])
    if @situation.update(situation_params)
      redirect_to edit_story_situation_path(@story, @situation)
    else
      render edit_story_situation(@story, @situation)
    end

  end

  def return_situation
    # render json: {tamere: "le slip"} and return
    render json: {situation: Situation.first} and return
    # return Situation.first
  end

  private
  def situation_params
    params.require(:situation).permit(:description)
  end

  def choice_params
    params.require(:situation).permit(:previous_choice)
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  skip_before_action :authenticate_user!


  def index

    @stories = Story.all

  end

  def new
    @story = Story.new
  end

  def create
    @story = Story.new(story_params)
    if @story.save
      redirect_to story_path(@story)
    else
      render :new
    end
  end

  def show
    @story = Story.find(params[:id])

    unless StartSituation.where(story: @story).first.nil?
      @story_start_situation = StartSituation.where(story: @story).first.situation
    else
      @story_start_situation = nil
    end

  end

  private
  def story_params
    params.require(:story).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%#= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container centered-vertically banner">
  <h1 class="main-title">Binary</h1>

  <div class="options-container">
    <%= link_to "All Stories", stories_path, class: "comics-btn" %>
    <%= link_to "New Story", new_story_path, class: "comics-btn" %>
  </div>
</div>

app/views/pages/tests.html.erb
<div id="mind-mapper">
  <table id="mind-table">
    <% 20.times do %>
      <tr>
        <% 20.times do %>
        <td></td>
        <% end %>
      </tr>
    <% end %>
  </table>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/situations/edit.html.erb
<div class="structure-container">

  <div class="structure-sidenav">

    <% if @previous_situation %>
      <%= link_to edit_story_situation_path(@story, @previous_situation) do %>
        <i class="fas fa-backward"></i>
      <% end %>
    <% else %>
      <%= link_to story_path(@story) do %>
        <i class="fas fa-backward"></i>
      <% end %>
    <% end %>

    <%= link_to story_situation_path(@story, @situation) do %>
      <i class="fas fa-book-open"></i>
    <% end %>


    <%= link_to stories_path do %>
      <i class="fas fa-home"></i>
    <% end %>

  </div>






  <div class="structure-content">

    <div class="structure-title-container">
      <h2><%= @story.name %></h2>
    </div>

    <div class="rounded-container">
      <div class="situation-container">
        <p><%= @situation.description %></p>
        <div class="situation-options">
          <div class="edit-situation-btn">
            <i class="fas fa-edit"></i>
          </div>
          <%#= link_to story_situation_choice_path(@story, @situation, choice), method: :delete, data: { confirm: "Are you sure?" } do%>
            <!-- <i class="far fa-trash-alt"></i> -->
          <%# end %>
        </div>

        <div class="situation-edition">
          <%= simple_form_for [ @story, @situation ] do |f| %>
            <%#= f.label :description, "Edit Situation" %>
            <%= f.input :description, :as => :text, label: false, :input_html => { class: "situation-container" } %>
            <%#= f.button :submit, "Submit changes", class: "oval-bordered-button" %>
            <div class="valid-cancel-container">
              <i class="fas fa-times cancel-situation-edition"></i>
              <%= button_tag type: 'submit', class: "button-icon" do %>
                <i class="fas fa-check"></i>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="choices">

      <% @child_choices.each_with_index do |choice, index| %>

        <% if choice.next_situation %>

          <div class="rounded-container choice">
            <%= link_to edit_story_situation_path(@story, choice.next_situation) do  %>
              <div class="choice-clickable-top">
                <h3>Choice <%= index +1 %></h3>
                <p><%= choice.description %></p>
                <div class="choice-ico green">
                <i class="fas fa-circle"></i>
              </div>
            </div>
            <% end %>
            <div class="choice-edition" data-choice="<%= index %>">
              <%= simple_form_for [ @story, @situation, choice ] do |f| %>
                <%= f.input :description, :as => :text, label: false%>
                <%#= f.button :submit, "Submit changes", class: "oval-bordered-button" %>
                <div class="valid-cancel-container">
                  <i class="fas fa-times cancel-choice-edition" data-choice="<%= index %>"></i>
                  <%= button_tag type: 'submit', class: "button-icon" do %>
                    <i class="fas fa-check"></i>
                  <% end %>
                </div>
              <% end %>
            </div>
            <div class="choice-options" data-choice="<%= index %>">
              <%= link_to edit_story_situation_path(@story, choice.next_situation) do  %>
                <i class="fas fa-forward"></i>
              <% end %>
              <div class="edit-choice-btn" data-choice="<%= index %>">
                <i class="fas fa-edit"></i>
              </div>
              <%= link_to story_situation_choice_path(@story, @situation, choice), method: :delete, data: { confirm: "Are you sure?" } do%>
                <i class="far fa-trash-alt"></i>
              <% end %>
            </div>
          </div>

        <% else %>

          <div class="rounded-container choice">
            <%= link_to new_story_situation_path(@story, choice: choice.id) do  %>
              <div class="choice-clickable-top">
                <h3>Choice <%= index +1 %></h3>
                <p><%= choice.description %></p>
                <div class="choice-ico red">
                  <i class="fas fa-circle"></i>
                </div>
              </div>
            <% end %>
            <div class="choice-edition" data-choice="<%= index %>">
              <%= simple_form_for [ @story, @situation, choice ] do |f| %>
                <%= f.input :description, :as => :text, label: false%>
                <%#= f.button :submit, "Submit changes", class: "oval-bordered-button" %>
                <div class="valid-cancel-container">
                  <i class="fas fa-times cancel-choice-edition" data-choice="<%= index %>"></i>
                  <%= button_tag type: 'submit', class: "button-icon" do %>
                    <i class="fas fa-check"></i>
                  <% end %>
                </div>
              <% end %>
            </div>
            <div class="choice-options" data-choice="<%= index %>" >
              <%= link_to new_story_situation_path(@story, choice: choice.id) do  %>
                <i class="fas fa-forward"></i>
              <% end %>
              <div class="edit-choice-btn" data-choice="<%= index %>">
                <i class="fas fa-edit"></i>
              </div>
              <%= link_to story_situation_choice_path(@story, @situation, choice), method: :delete, data: { confirm: "Are you sure?" } do%>
                <i class="far fa-trash-alt"></i>
              <% end %>
            </div>

          </div>

        <% end %>
      <% end %>

      <div class="rounded-container" id="add-choice-form">
        <h3>Choice <%= @child_choices.length + 1 %></h3>
        <%= simple_form_for [ @story, @situation, @choice ] do |f| %>
          <%= f.input :description, label: false %>
          <%= f.button :submit, "Add a choice", class: "oval-bordered-button" %>
        <% end %>
      </div>

      <div class="add-new-choice-container centered-vertically">
        +
      </div>
    </div>

  </div>

</div>

app/views/situations/new.html.erb
<div class="structure-container">

  <div class="structure-sidenav">

    <% if @previous_situation %>
      <%= link_to story_situation_path(@story, @previous_situation) do %>
        <i class="fas fa-backward"></i>
      <% end %>
    <% else %>
      <%= link_to story_path(@story) do %>
        <i class="fas fa-backward"></i>
      <% end %>
    <% end %>


    <!-- %#= link_to edit_story_situation_path(@story, @situation) do  %>
      <i class="fas fa-edit"></i>
    <%# end %> -->


    <%= link_to stories_path do %>
      <i class="fas fa-home"></i>
    <% end %>

  </div>

  <div class="structure-content">

    <div class="structure-title-container">
      <h2>Nouvelle Situation</h2>
    </div>

    <div class="rounded-container">
        <%= simple_form_for [ @story, @situation ] do |f| %>
          <% if params[:choice] %>
            <%= f.hidden_field :previous_choice, value: params[:choice] %>
          <% end %>
          <%= f.input :description %>
          <%= f.button :submit %>
        <% end %>
    </div>
  </div>

</div>

app/views/situations/show.html.erb
<div class="structure-container">

  <div class="structure-sidenav">

    <% if @previous_situation %>
      <%= link_to story_situation_path(@story, @previous_situation) do %>
        <i class="fas fa-backward"></i>
      <% end %>
    <% else %>
      <%= link_to story_path(@story) do %>
        <i class="fas fa-backward"></i>
      <% end %>
    <% end %>


    <%= link_to edit_story_situation_path(@story, @situation) do  %>
      <i class="fas fa-edit"></i>
    <% end %>


    <%= link_to stories_path do %>
      <i class="fas fa-home"></i>
    <% end %>

  </div>

  <div class="structure-content">

    <div class="structure-title-container">
      <h2><%= @story.name %></h2>
    </div>

    <div class="choices">
      <% @child_choices.each_with_index do |choice, index| %>
        <% if choice.next_situation %>
          <%= link_to story_situation_path(@story, choice.next_situation) do  %>
            <div class="rounded-container choice">
              <h3>Choice <%= index +1 %></h3>
              <p><%= choice.description %></p>
              <div class="choice-ico green">
                <i class="fas fa-circle"></i>
              </div>
            </div>
          <% end %>
        <% else %>
          <%= link_to new_story_situation_path(@story, choice: choice.id) do  %>
            <div class="rounded-container choice">
              <h3>Choice <%= index +1 %></h3>
              <p><%= choice.description %></p>
              <div class="choice-ico red">
                <i class="fas fa-circle"></i>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>

    <div class="rounded-container white">
      <%= @situation.description %>
    </div>

    <div class="rounded-container">
      <% loop do %>
        <% @loop_start_parent = @loop_start.parent_choice %>
        <% break if @loop_start_parent.nil? %>
        <!-- <p> - <%#= @loop_start.description %></p> -->
        <% @loop_start = @loop_start_parent.previous_situation %>
        <div class="choices">
          <% @loop_start.child_choices.sort_by{|c| c.id}.each_with_index do |choice, index| %>
            <% if choice ==  @loop_start_parent %>
              <div class="rounded-container choice selected">
                <h3>Choice <%= index +1 %></h3>
                <p><%= choice.description %></p>
              </div>
            <% else %>
              <div class="rounded-container choice">
                <h3>Choice <%= index +1 %></h3>
                <p><%= choice.description %></p>
              </div>
            <% end %>
          <% end %>
        </div>
        <% break if @loop_start.nil? %>
        <p> - <%= @loop_start.description %></p>
      <% end %>
    </div>

  </div>

</div>

app/views/stories/index.html.erb
<div class="structure-container">

  <div class="structure-sidenav">
    <%= link_to root_path do %>
      <i class="fas fa-home"></i>
    <% end %>

    <%= link_to new_story_path do %>
      <i class="fas fa-plus-circle"></i>
    <% end %>

  </div>

  <div class="structure-content">

    <div class="structure-title-container">
      <h2>All Stories</h2>
    </div>


    <div class="story-cards">
      <% @stories.each do |story| %>
        <%= link_to story_path(story) do %>
          <div class="rounded-container story-card">
            <h3><%= story.name %></h3>
            <p>Description: <%= story.description %></p>
            <p><%= story.situations.count %> Situations on this story</p>
          </div>
        <% end %>
      <% end %>
    </div>

  </div>

</div>

app/views/stories/new.html.erb
<div class="container centered-vertically full-screen-height">
  <h1>Create a new story :</h1>
  <%= simple_form_for @story,html: { class: "rounded-container centered-vertically"} do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.button :submit, class: "oval-bordered-button" %>
  <% end %>
</div>

app/views/stories/show.html.erb
<!--
création d´ une situation initiale
donc création d´ une situation
création de 2 choix -->

<div class="structure-container">

  <div class="structure-sidenav">
    <%= link_to stories_path do %>
      <i class="fas fa-home"></i>
    <% end %>
  </div>

  <div class="structure-content">

    <div class="structure-title-container">
      <h2><%= @story.name %></h2>
    </div>

    <div class="rounded-container">
      <p>Story Description: <%= @story.description %></p>
      <p><%= @story.situations.count %> Situations on this story</p>
    </div>

    <% if @story.situations.count == 0 %>
      <%= link_to "Create the first situation for this story", new_story_situation_path(@story), class: "oval-bordered-button" %>
    <% else %>
      <%= link_to "Go to initial situation", story_situation_path(@story, @story_start_situation), class: "oval-bordered-button"  %>
    <% end %>

  </div>

</div>